package com.aje.download.client;

import java.net.MalformedURLException;
import java.net.URL;

import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;

import com.aje.common.WSConnectString;

/**
 * This class was generated by the JAX-WS RI. JAX-WS RI 2.2.3-b01- Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "FileServerImplService", targetNamespace = "http://ws.download.aje.com/", wsdlLocation = "http://localhost:9899/ws/file?wsdl")
public class FileServerImplService extends Service {
  
  private final static URL FILESERVERIMPLSERVICE_WSDL_LOCATION;
  private final static WebServiceException FILESERVERIMPLSERVICE_EXCEPTION;
  private final static QName FILESERVERIMPLSERVICE_QNAME = new QName("http://ws.download.aje.com/",
      "FileServerImplService");

  static {
    URL url = null;
    WebServiceException e = null;
    WSConnectString wsCon = new WSConnectString();
    try {
      // url = new URL("http://localhost:9899/ws/file?wsdl");
      //url = new URL("http://172.20.0.61:8080/WSAjeCFDI/download?wsdl");
    	url = new URL(wsCon.getServiceGetPDF());
    } catch (MalformedURLException ex) {
      e = new WebServiceException(ex);
    }
    FILESERVERIMPLSERVICE_WSDL_LOCATION = url;
    FILESERVERIMPLSERVICE_EXCEPTION = e;
  }

  public FileServerImplService() {
    super(__getWsdlLocation(), FILESERVERIMPLSERVICE_QNAME);
  }

  public FileServerImplService(WebServiceFeature... features) {
    super(__getWsdlLocation(), FILESERVERIMPLSERVICE_QNAME, features);
  }

  public FileServerImplService(URL wsdlLocation) {
    super(wsdlLocation, FILESERVERIMPLSERVICE_QNAME);
  }

  public FileServerImplService(URL wsdlLocation, WebServiceFeature... features) {
    super(wsdlLocation, FILESERVERIMPLSERVICE_QNAME, features);
  }

  public FileServerImplService(URL wsdlLocation, QName serviceName) {
    super(wsdlLocation, serviceName);
  }

  public FileServerImplService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
    super(wsdlLocation, serviceName, features);
  }

  /**
   * 
   * @return returns FileServer
   */
  @WebEndpoint(name = "FileServerImplPort")
  public FileServer getFileServerImplPort() {
    return super.getPort(new QName("http://ws.download.aje.com/", "FileServerImplPort"),
        FileServer.class);
  }

  /**
   * 
   * @param features
   *          A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy. Supported
   *          features not in the <code>features</code> parameter will have their default values.
   * @return returns FileServer
   */
  @WebEndpoint(name = "FileServerImplPort")
  public FileServer getFileServerImplPort(WebServiceFeature... features) {
    return super.getPort(new QName("http://ws.download.aje.com/", "FileServerImplPort"),
        FileServer.class, features);
  }

  private static URL __getWsdlLocation() {
    if (FILESERVERIMPLSERVICE_EXCEPTION != null) {
      throw FILESERVERIMPLSERVICE_EXCEPTION;
    }
    return FILESERVERIMPLSERVICE_WSDL_LOCATION;
  }

}
