package com.aje.download.client;

import java.net.MalformedURLException;
import java.net.URL;

import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;

import com.aje.common.WSConnectString;

/**
 * This class was generated by the JAX-WS RI. JAX-WS RI 2.2.3-b01- Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "FileTextImplService", targetNamespace = "http://ws.download.aje.com/", wsdlLocation = "http://localhost:9899/ws/file?wsdl")
public class FileTextImplService extends Service {

  private final static URL FILETEXTIMPLSERVICE_WSDL_LOCATION;
  private final static WebServiceException FILETEXTIMPLSERVICE_EXCEPTION;
  private final static QName FILETEXTIMPLSERVICE_QNAME = new QName("http://ws.download.aje.com/",
      "FileTextImplService");

  static {
    URL url = null;
    WebServiceException e = null;
    WSConnectString wsCon = new WSConnectString();
    try {
      // url = new URL("http://localhost:9899/ws/file?wsdl");
      //url = new URL("http://172.20.0.61:8080/WSAjeCFDI/create?wsdl");
    	url = new URL(wsCon.getServiceCreateFileText());
    } catch (MalformedURLException ex) {
      e = new WebServiceException(ex);
    }
    FILETEXTIMPLSERVICE_WSDL_LOCATION = url;
    FILETEXTIMPLSERVICE_EXCEPTION = e;
  }

  public FileTextImplService() {
    super(__getWsdlLocation(), FILETEXTIMPLSERVICE_QNAME);
  }

  public FileTextImplService(WebServiceFeature... features) {
    super(__getWsdlLocation(), FILETEXTIMPLSERVICE_QNAME, features);
  }

  public FileTextImplService(URL wsdlLocation) {
    super(wsdlLocation, FILETEXTIMPLSERVICE_QNAME);
  }

  public FileTextImplService(URL wsdlLocation, WebServiceFeature... features) {
    super(wsdlLocation, FILETEXTIMPLSERVICE_QNAME, features);
  }

  public FileTextImplService(URL wsdlLocation, QName serviceName) {
    super(wsdlLocation, serviceName);
  }

  public FileTextImplService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
    super(wsdlLocation, serviceName, features);
  }

  /**
   * 
   * @return returns FileServer
   */
  @WebEndpoint(name = "FileTextImplPort")
  public FileText getFileTextImplPort() {
    return super.getPort(new QName("http://ws.download.aje.com/", "FileTextImplPort"),
        FileText.class);
  }

  /**
   * 
   * @param features
   *          A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy. Supported
   *          features not in the <code>features</code> parameter will have their default values.
   * @return returns FileServer
   */
  @WebEndpoint(name = "FileTextImplPort")
  public FileText getFileTextImplPort(WebServiceFeature... features) {
    return super.getPort(new QName("http://ws.download.aje.com/", "FileTextImplPort"),
        FileText.class, features);
  }

  private static URL __getWsdlLocation() {
    if (FILETEXTIMPLSERVICE_EXCEPTION != null) {
      throw FILETEXTIMPLSERVICE_EXCEPTION;
    }
    return FILETEXTIMPLSERVICE_WSDL_LOCATION;
  }

}
